//Index para seccion Inventario
export const GET_INVENTARIO = "GET_INVENTARIO";
export const SHOW_FORM_INV = "SHOW_FORM_INV";
export const ADD_SELECT_TALLAS = "ADD_SELECT_TALLAS";
export const UPDATE_SELECT_TALLAS = "UPDATE_SELECT_TALLAS";
export const REMOVE_SELECT_TALLAS = "REMOVE_SELECT_TALLAS";
export const CLOSE_FORM_INVENTARIO = "CLOSE_FORM_INVENTARIO";
export const ADD_MOVIMIENTO_INVENTARIO = "ADD_MOVIMIENTO_INVENTARIO";
export const SEARCH_DATA_PRODUCTO = "SEARCH_DATA_PRODUCTO";
export const SHOW_ERROR_FORM_INV = "SHOW_ERROR_FORM_INV";
export const SHOW_LIST_TALLAS = "SHOW_LIST_TALLAS";
export const CLOSE_CODE_FORM = "CLOSE_CODE_FORM";
export const SHOW_CODE_FORM = "SHOW_CODE_FORM";
export const GET_MOVIMIENTO_INV = "GET_MOVIMIENTO_INV";
export const UPDATE_MOVIMIENTO_INVENTARIO = "UPDATE_MOVIMIENTO_INVENTARIO";
export const SHOW_TALLAS_TO_UPDATE = "SHOW_TALLAS_TO_UPDATE";
export const DELETE_MOVIMIENTO_INVENTARIO = "DELETE_MOVIMIENTO_INVENTARIO";

//Index para seccion Proveedor
export const CLOSE_FORM_PROVEEDOR = "CLOSE_FORM_PROVEEDOR";
export const SHOW_FORM_PROV = "SHOW_FORM_PROV";
export const SHOW_ERR_FORM_PROV = "SHOW_ERR_FORM_PROV";
export const ADD_PROVEEDOR = "ADD_PROVEEDOR";
export const SHOW_MENU_ACTION_PROV = "SHOW_MENU_ACTION_PROV";
export const CLOSE_MENU_ACTION_PROV = "CLOSE_MENU_ACTION_PROV";
export const SELECT_PROVEEDOR = "SELECT_PROVEEDOR";
export const UPDATE_PROVEEDOR = "UPDATE_PROVEEDOR";
export const CLEAR_SELECTED_PROV = "CLEAR_SELECTED_PROV";
export const DELETE_PROVEEDOR = "DELETE_PROVEEDOR";
export const GET_PROVEEDOR = "GET_PROVEEDOR";
export const GET_STOCK = "GET_STOCK";

//Index para seccion Productos
export const SELECT_COLOR = "SELECT_COLOR";
export const SHOW_LIST_COLORS = "SHOW_LIST_COLORS";
export const CLOSE_LIST_COLORS = "CLOSE_LIST_COLORS";
export const CLOSE_FORM_PRODUCTO = "CLOSE_FORM_PRODUCTO";
export const OPEN_FORM_PRODUCTO = "OPEN_FORM_PRODUCTO";
export const EXIST_ERROR_FORM = "EXIST_ERROR_FORM";
export const INSERT_PRODUCT = "INSERT_PRODUCT";
export const SHOW_MENU_ACTION_PROD = "SHOW_MENU_ACTION_PROD";
export const CLOSE_MENU_ACTION_PROD = "CLOSE_MENU_ACTION_PROD";
export const SELECT_PRODUCTO = "SELECT_PRODUCTO";
export const UPDATE_PRODUCTO = "UPDATE_PRODUCTO";
export const CLEAR_SELECTED_PROD = "CLEAR_SELECTED_PROD";
export const DELETE_PRODUCTO = "DELETE_PRODUCTO";
export const BUSCAR_PRODUCTO = "OBTENER_PROD_INVENTARIO";

//Index para seccion Vendedores
export const SHOW_FORM_VENDEDOR = "SHOW_FORM_VENDEDOR";
export const CLOSE_FORM_VENDEDOR = "CLOSE_FORM_VENDEDOR";
export const SHOW_ERR_FORM_VENDEDOR = "SHOW_ERR_FORM_VENDEDOR";
export const ADD_VENDEDOR = "ADD_VENDEDOR";
export const SHOW_MENU_ACTION_VENDEDOR = "SHOW_MENU_ACTION_VENDEDOR";
export const CLOSE_MENU_ACTION_VENDEDOR = "CLOSE_MENU_ACTION_VENDEDOR";
export const SELECT_VENDEDOR = "SELECT_VENDEDOR";
export const UPDATE_VENDEDOR = "UPDATE_VENDEDOR";
export const CLEAR_SELECTED_VENDEDOR = "CLEAR_SELECTED_VENDEDOR";
export const DELETE_VENDEDOR = "DELETE_VENDEDOR";
export const GET_VENDEDOR = "GET_VENDEDOR";

//index para la parte de MODALS
export const SHOW_MODAL = "SHOW_MODAL";
export const HIDE_MODAL = "HIDE_MODAL";
export const YES_DELETE = "YES_DELETE";
export const DELETE_CLEAR = "DELETE_CLEAR";
//index para las alertas dentro del context Modals
export const SHOW_ALERT = "SHOW_ALERT";
export const HIDE_ALERT = "HIDE_ALERT";

//----------------------- context AUTENTICACION ----------------------------------
export const REGISTRO_EXITOSO = "REGISTRO_EXITOSO";
export const REGISTRO_ERROR = "REGISTRO_ERROR";
export const OBTENER_USUARIO = "OBTENER_USUARIO";
export const LOGIN_EXITOSO = "LOGIN_EXITOSO";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const CERRAR_SESION = "CERRAR_SESION";
